# Generated by Django 3.0.7 on 2020-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='lastname',
            field=models.CharField(default='last_name', max_length=32),
        ),
        migrations.AddField(
            model_name='info',
            name='password',
            field=models.CharField(default='pass_word', max_length=32),
        ),
        migrations.AddField(
            model_name='info',
            name='username',
            field=models.CharField(default='user_name', max_length=32),
        ),
    ]
