# Generated by Django 3.0.7 on 2020-06-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200610_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='lastname',
            field=models.CharField(max_length=32),
        ),
    ]
