# Generated by Django 3.0.7 on 2020-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=300)),
                ('page_name', models.CharField(max_length=100)),
                ('page_traffic', models.FloatField(default=0)),
                ('page_status', models.IntegerField(default=0)),
                ('page_rank', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=300)),
                ('stats', models.FloatField()),
            ],
        ),
    ]
