# Generated by Django 3.0.3 on 2020-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPageTester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=300)),
                ('page_name', models.CharField(max_length=100)),
                ('links_in_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=300)),
                ('page_name', models.CharField(max_length=100)),
                ('median_load_time', models.IntegerField(default=0)),
                ('percentile', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_traffic',
            new_name='page_views_per_million',
        ),
        migrations.AddField(
            model_name='page',
            name='page_views_per_user',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='reach_per_million',
            field=models.FloatField(default=0),
        ),
    ]
