# Generated by Django 3.0.3 on 2020-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPageTester', '0002_auto_20200609_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_signups',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_traffic',
            field=models.FloatField(null=True),
        ),
    ]
