# Generated by Django 3.0.7 on 2020-06-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPageTester', '0003_auto_20200611_1245'),
        ('landingPageTester', '0003_auto_20200611_1330'),
    ]

    operations = [
    ]
