# Generated by Django 3.0.7 on 2020-06-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPageTester', '0004_merge_20200611_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigureDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=300)),
                ('company_format', models.CharField(max_length=300)),
                ('token', models.CharField(max_length=300)),
            ],
        ),
    ]
