# Generated by Django 3.0.3 on 2020-06-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPageTester', '0004_auto_20200609_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_rank',
            field=models.BigIntegerField(default=0),
        ),
    ]
