# Generated by Django 3.0.3 on 2020-06-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPageTester', '0005_page_page_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_signups',
        ),
    ]
